Factor out data transformations
cryspen/atlas pull request #35
Opened 2023-10-12 15:10 UTC by jschneider-bensch

As a first step towards a cleaner spec, that can be more closely matched to e.g. the ProVerif model, I've factored out the transformations that need to happen to pairs of identifiers/pseudonyms (I've introduced the term `handle` here) and data values, plain or encrypted.

At the moment it's a bit awkward because the table data structures don't know about these sorts of pairs yet, but that should be fixed together with #18 .

2023-10-13 08:01 UTC, franziskuskiefer requested changes
Thanks, looks good with some nits.

2023-10-13 10:03 UTC, jschneider-bensch commented on hacspec-scrambledb/scrambledb/src/data_types.rs
> +pub struct IdentifiableDatum {
My intent was to emphasize that this is about individual pieces of data, but yeah it does sound odd. I've changed it to -`Data`.

2023-10-13 10:04 UTC, jschneider-bensch commented on hacspec-scrambledb/scrambledb/src/data_transformations.rs
> +    let encrypted_data_value = EncryptedDataValue {
For now, I chose not to introduce a constructor method.

2023-10-13 10:04 UTC, jschneider-bensch commented on hacspec-scrambledb/scrambledb/src/data_transformations.rs
> +        handle: blinded_handle,
I've changed the field names accordingly.

2023-10-13 10:05 UTC, jschneider-bensch commented on hacspec-scrambledb/scrambledb/src/data_transformations.rs
> +        value: SerializedHPKE::from_hpke_ct(&HpkeSeal(
I've pulled out the double encryption and decryption into their own module.

2023-10-13 10:05 UTC, jschneider-bensch commented on hacspec-scrambledb/scrambledb/src/data_transformations.rs
> +    b"CoPRF-Context-Pseudonymization".to_vec()
Indeed, they should be `const`s. I've changed it accordingly.

2023-10-13 10:06 UTC, jschneider-bensch commented on hacspec-scrambledb/scrambledb/src/data_transformations.rs
> +    bpk: &BlindingPublicKey,
I'll have to make this consistent one way or the other across the spec in a follow up.

2023-10-15 19:12 UTC, franziskuskiefer approved these changes
Thanks!

2023-10-15 19:13 UTC, merged